### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by PwrSystmsRy** [kqshan/vcg-auction#1]
There seems to be an error with your script - it only seems to partially run.
I get this error using both your example input file and my own input file. I have tried executing the script on python 2 and 3.

Any suggestions?

The error is shown below:

    print(prob)
  File "C:\Users\ryan\Desktop\VCG\vcg-auction-master\vcg_auction.py", line 230, in __str__
    width = max([len(x.name) for x in self.bidders], default=8)
TypeError: max() got an unexpected keyword argument

Thanks

**Comment by kqshan** [comment]
What version of Python are you running? Can you try with 3.4 or newer? The `default` keyword argument was added to the `max()` function in 3.4, and I believe that's the error that you're getting.

**Comment by PwrSystmsRy** [comment]
Hi,

I have your script with Python 3.7.0 and 2.7.15
Any other suggestions?

**Comment by PwrSystmsRy** [comment]
Sorted - Python 3.4 works perfectly!!
Great script.
Thanks!
